config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#home'

  get 'about', to: 'static_pages#about'

  authenticate :user do
    get 'overview', to: 'static_pages#overview'
    get 'search', to: 'static_pages#search'

    resource :settings, only: [:edit, :update]

    resources :sites do

      resources :devices do
        member { get :assign }
        resources :repairs
      end

      resources :supplies do
        member { get :assign, :history, :use }
      end
    end

    get 'all_devices', to: 'devices#all'
    get 'export_devices', to: 'devices#export'
    get 'all_supplies', to: 'supplies#all'
    get 'export_supplies', to: 'supplies#export'

  end

  authenticate :user, lambda { |u| u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
    resources :users_admin, controller: 'users'
  end

end

app/models/device.rb
class Device < ApplicationRecord
  resourcify
  has_many :device_supplies
  has_many :supplies, through: :device_supplies
  has_many :repairs
  belongs_to :site

  validates :name, presence: true, uniqueness: { scope: :site,
                                                 case_sensitive: false }
  validates :devtype, presence: true
  validates :status, presence: true

  before_save :remove_location_if_inactive, if: :status_changed?, on: :update

  scope :in_repair, -> { where(status: "In Repair").order("name") }

  searchkick word_middle: [:name], callbacks: :async

  DEVICE_TYPES = ['Printer', 'Scanner', 'Other']
  DEVICE_STATUSES = ['Active', 'Inactive', 'In Repair']

  def search_data
    {
      name: name,
      sn: sn,
      asset_tag: asset_tag
    }
  end

  private

  def remove_location_if_inactive
    self.location = "" if self.status == "Inactive"
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  load_and_authorize_resource

  def index
    @site = Site.find(params[:site_id])
    @devices = @site.devices.order("name")
  end

  def all
    @devices = Device.includes(:site).accessible_by(current_ability).order("name")
    redirect_to root_path unless Site.any?
  end

  def show
    @site = Site.find(params[:site_id])
    @device = @site.devices.find(params[:id])
    @device_supplies = @device.supplies.includes(:site).order("name")
    @repairs = @device.repairs.limit(5).order("created_at DESC")
  end

  def new
    @site =  Site.find(params[:site_id])
    @device = @site.devices.build
  end

  def edit
    @site =  Site.find(params[:site_id])
    @device = @site.devices.find(params[:id])
  end

  def create
    @site =  Site.find(params[:site_id])
    @device = @site.devices.build(device_params)
    if @device.save
      flash[:success] = "Device added"
      redirect_to site_devices_path(@site)
    else
      render 'new'
    end
  end

  def update
    @site = Site.find(params[:site_id])
    @device = Device.find(params[:id])
    if @device.update_attributes(device_params)
      flash[:success] = "#{@device.name} saved"
      # Device status changes to 'In Repair'
      if @device.previous_changes.any? && @device.previous_changes["status"][1] == "In Repair"
        redirect_to new_site_device_repair_path(@site, @device)
      # Device status changes from 'In Repair' to something else
      elsif @device.repairs.any? && @device.previous_changes.any? && @device.previous_changes["status"][0] == "In Repair"
        redirect_to edit_site_device_repair_path(@site, @device, @device.repairs.last)
      else
        redirect_to site_device_path(@site, @device)
      end
    else
      render 'edit'
    end
  end

  def destroy
    Device.find(params[:id]).destroy
    flash[:warning] = "Device deleted"
    redirect_to site_devices_path
  end

  def assign
    @site = Site.find(params[:site_id])
    @device = @site.devices.find(params[:id])
    @supplies = @site.supplies.order("name")
  end

  def export
    if params[:repair]
      @devices = Device.includes(:site).in_repair.accessible_by(current_ability)
    elsif params[:all]
      @devices = Device.includes(:site).accessible_by(current_ability)
    else
      @site = Site.find(params[:site_id])
      @devices = @site.devices
    end

    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"Devices.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  private

  def device_params
    params.require(:device).permit(:name, :devtype, :model, :status, :ip,
                                   :location, :sn, :asset_tag, :notes, :site_id,
                                   supply_ids: [])
  end

end

app/views/devices/all.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">

        <i class="material-icons left">print</i>

        <!-- Card title -->
        <span class="card-title">All Devices</span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-devices-all" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-devices-all" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button-->
          <li>
            <%= link_to export_devices_path(all: true, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>
        </ul>

        <% if @devices.any? %>

          <%= table_for_devices(@devices) %>

        <% else %>
          <h5 style="font-size: 1.3em;">Looks like you have no devices yet.</h5>
        <% end %>

      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/devices/assign.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">assignment</i>

        <!-- Card title -->
        <span class="card-title"><%= @device.name %> - Assign Supplies</span>

        <div class="container">

          <%= form_for [@site, @device] do |f| %>

            <table class="highlight">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Vendor</th>
                  <th>Description</th>
                  <th>Quantity</th>
                </tr>
              </thead>

              <tbody>

                <!-- Needed for successful update if no supplies assigned -->
                <%= hidden_field_tag "device[supply_ids][]" %>

                <% @supplies.each do |supply| %>
                  <tr>
                    <td>

                      <!-- f.object.supplies.include?(supply) used to set checkbox status, but generates N+1 Query problem. Not sure how to fix that yet. -->
                      <%= check_box_tag "device[supply_ids][]", supply.id, f.object.supplies.include?(supply), id: "device_supply_ids_#{supply.id}" %>
                      <label for="device_supply_ids_<%= supply.id %>"><%= supply.name %></label>
                    </td>
                    <td><%= supply.vendor %></td>
                    <td><%= supply.description %></td>
                    <td><%= supply.quantity %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <!-- Buttons -->

            <!-- Uncheck all button -->
            <div class="row">
              <div class="col s12" style="margin-top: 10px; margin-bottom: 10px;">
                <a id="uncheck-all" href="javascript:void(0);" class="btn btn-flat">Uncheck All</a>
              </div>
            </div>

            <div class="row">
              <div class="col s12">

                <!-- Save button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Save" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", site_device_path(@site, @device), class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>  <!-- Buttons -->

          <% end %>  <!-- Form end -->

        </div>  <!-- Form container -->
      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<!-- Uncheck all checkboxes function -->
<script>
  $(document).ready(function() {
    $('#uncheck-all').click(function(){
      $('input:checkbox').attr('checked', false);
    });
  });
</script>

app/views/devices/edit.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">print</i>

        <!-- Device name -->
        <span class="card-title">Edit: <%= @device.name %></span>

        <div class="container">

          <%= form_for [@site, @device] do |f| %>

            <%= form_errors_for @device %>

            <!-- Name -->
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :name, class: "active" %>
                <%= f.text_field :name, required: true %>
              </div>
            </div>

            <div class="row">

              <!-- Type -->
              <div class="input-field col s6">
                <%= f.label :devtype, "Type", class: "active" %>
                <%= f.select :devtype, Device::DEVICE_TYPES %>
              </div>

              <!-- Status -->
              <div class="input-field col s6" id="status">
                <%= f.label :status, class: "active" %>
                <%= f.select :status, Device::DEVICE_STATUSES %>
              </div>
            </div>

            <div class="row">

              <!-- Model -->
              <div class="input-field col s6">
                <%= f.label :model, class: "active" %>
                <%= f.text_field :model %>
              </div>

              <!-- IP -->
              <div class="input-field col s6">
                <%= f.label :ip, "WebUI Address", class: "active" %>
                <%= f.text_field :ip %>
              </div>
            </div>

            <div class="row">

              <!-- Serial Number -->
              <div class="input-field col s6">
                <%= f.label :sn, "Serial Number", class: "active" %>
                <%= f.text_field :sn %>
              </div>

              <!-- Asset Tag -->
              <div class="input-field col s6">
                <%= f.label :asset_tag, "Asset Tag", class: "active" %>
                <%= f.text_field :asset_tag %>
              </div>
            </div>

            <!-- Location -->
            <div class="row" id="location">
              <div class="input-field col s12">
                <%= f.label :location, class: "active" %>
                <%= f.text_field :location %>
              </div>
            </div>

            <!-- Notes -->
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :notes, "Notes", class: "active" %>
                <%= f.text_field :notes %>
              </div>
            </div>

            <!-- Buttons -->
            <div class="row">
              <div class="col s12">

                <!-- Save button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Save" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", site_device_path(@site, @device), class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>  <!-- Buttons -->

          <% end %>

        </div>  <!-- Form container -->

        <!-- Delete device button -->
        <div class="row">
          <div class="col s12">
            <%= button_to "Delete device", site_device_path(@site, @device), data: { confirm: "Are you sure? You're about to delete this device. This action is irreversible." }, method: :delete, class: "btn btn-flat waves-effect waves-red red-text" %>
          </div>
        </div>

      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<script>
  $(document).ready(function() {
    var initialText = $('#status :selected').text();
    if (initialText === "Inactive") { $('#location').hide(); }

    $('#status').change(function () {
      var selected = $('#status :selected').text();
      if (selected === "Inactive") { $('#location').hide(); }
      else { $('#location').show(); }
    });
  });
</script>

app/views/devices/export.csv.erb
<% headers = ['Name', 'Type', 'Model', 'Location', 'Status', 'Serial Number',
              'Asset Tag', 'Supplies', 'Site'] %>
<%= CSV.generate_line(headers, { col_sep: "," }) %>
<%- @devices.each do |device| -%>
<%= CSV.generate_line( [ device.name, device.devtype, device.model,
                         device.status, device.location, device.sn, device.asset_tag,
                         device.supplies.pluck(:name).uniq.join("; "),
                         device.site.name ], {col_sep: ","} ).html_safe -%>
<% end %>

app/views/devices/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">

        <i class="material-icons left">print</i>

        <!-- Card title -->
        <span class="card-title"><%= @site.name %> - All Devices</span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-devices-all" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-devices-all" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button-->
          <li>
            <%= link_to export_devices_path(site_id: @site, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>

        </ul>

        <%= table_for_devices(@devices) %>

      </div>  <!-- Card content -->

      <div class="card-action">

        <!-- Back button -->
        <%= link_to "Back", sites_path, class: "btn btn-flat waves-effect waves-light" %>
      </div>

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<div class="fixed-action-btn tooltipped" style="bottom: 45px; right: 24px;" data-position="left" data-delay="50" data-tooltip="Add Device">
  <%= link_to new_site_device_path(@site), class: "btn-floating btn-large red" do %>
    <i class="large material-icons">add</i>
  <% end %>
</div>

app/views/devices/new.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">print</i>

        <!-- Card title -->
        <span class="card-title"><%= @site.name %> - New Device</span>

        <div class="container">

          <%= form_for [@site, @device] do |f| %>

            <!-- Name -->
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :name %>
                <%= f.text_field :name, required: true, autofocus: true %>
              </div>
            </div>

            <div class="row">

              <!-- Type -->
              <div class="input-field col s6">
                <%= f.label :devtype, "Type", class: "active" %>
                <%= f.select :devtype, Device::DEVICE_TYPES %>
              </div>

              <!-- Status -->
              <div class="input-field col s6" id="status">
                <%= f.label :status, class: "active" %>
                <%= f.select :status, Device::DEVICE_STATUSES %>
              </div>
            </div>

            <div class="row">

              <!-- Model -->
              <div class="input-field col s6">
                <%= f.label :model %>
                <%= f.text_field :model %>
              </div>

              <!-- IP -->
              <div class="input-field col s6">
                <%= f.label :ip, "WebUI Address" %>
                <%= f.text_field :ip %>
              </div>
            </div>

            <div class="row">

              <!-- Serial Number -->
              <div class="input-field col s6">
                <%= f.label :sn, "Serial Number", class: "active" %>
                <%= f.text_field :sn %>
              </div>

              <!-- Asset Tag -->
              <div class="input-field col s6">
                <%= f.label :asset_tag, "Asset Tag", class: "active" %>
                <%= f.text_field :asset_tag %>
              </div>
            </div>

            <!-- Location -->
            <div class="row" id="location">
              <div class="input-field col s12">
                <%= f.label :location, class: "active" %>
                <%= f.text_field :location %>
              </div>
            </div>

            <!-- Notes -->
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :notes, "Notes" %>
                <%= f.text_field :notes %>
              </div>
            </div>

            <!-- Buttons -->
            <div class="row">
              <div class="col s12">

                <!-- Create button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Create" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", site_path(@site), class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>  <!-- Buttons -->

          <% end %>

        </div>  <!-- Form container -->
      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<script>
  $(document).ready(function() {
    var initialText = $('#status :selected').text();
    if (initialText == "Inactive") { $('#location').hide(); }

    $('#status').change(function () {
      var selected = $('#status :selected').text();
      if (selected == "Inactive") { $('#location').hide(); }
      else { $('#location').show(); }
    });
  });
</script>

app/views/devices/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">

      <div class="card-content">

        <i class="material-icons left">print</i>

        <!-- Device name -->
        <span class="card-title"><%= @device.name %></span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-device-<%= @device.id %>" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-device-<%= @device.id %>" class="dropdown-content" style="min-width: 150px;">


          <!-- Link to WebUI -->
          <li>
            <%= link_to "http://#{@device.ip}", target: "_blank" do %>
              <i class="material-icons left">public</i>
              WebUI
            <% end %>
          </li>

          <!-- Edit device button-->
          <li>
            <%= link_to edit_site_device_path(@site, @device) do %>
              <i class="material-icons left">edit</i>
              Edit
            <% end %>
          </li>
        </ul>

        <!-- Device information -->
        <div class="row">
          <div class="col s12">
            <table class="highlight">
              <thead>
                <tr>
                  <th>Type</th>
                  <th>Model</th>
                  <th>Status</th>
                  <th>Location</th>
                  <th>Serial Number</th>
                  <th>Asset Tag</th>
                  <th>Site</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= @device.devtype %></td>
                  <td><%= @device.model %></td>
                  <td>
                    <% if @device.status == "Inactive" %>
                      <i class="material-icons left">clear</i>
                    <% elsif @device.status == "In Repair" %>
                      <i class="material-icons left">build</i>
                    <% else %>
                      <i class="material-icons left">check</i>
                    <% end %>
                    <%= @device.status %>
                  </td>
                  <td><%= @device.location %></td>
                  <td><%= @device.sn %></td>
                  <td><%= @device.asset_tag %></td>
                  <td><%= link_to @device.site.name, @site %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <!-- Device notes -->
        <% if @device.notes && !@device.notes.empty?  %>
          <div class="row">
            <div class="col s12">
              <blockquote class="left"><%= @device.notes %></blockquote>
            </div>
          </div>
        <% end %>

        <%= render 'layouts/assets-popout-device' %>

      </div>  <!-- Card content -->

      <div class="card-action">

        <!-- Back button -->
        <%= link_to "Back", site_path(@site), class: "btn btn-flat waves-effect waves-light" %>
      </div>

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large red">
    <i class="material-icons">menu</i>
  </a>
  <ul>
    <li>
      <div class="tooltipped" data-position="left" data-delay="50" data-tooltip="Assign Supplies">
        <%= link_to assign_site_device_path(@site, @device), class: "btn-floating green" do %>
          <i class="material-icons">assignment</i>
        <% end %>
      </div>
    </li>
    <li>
      <div class="tooltipped" data-position="left" data-delay="50" data-tooltip="View Repairs">
        <%= link_to site_device_repairs_path(@site, @device), class: "btn-floating yellow darken-3" do %>
          <i class="material-icons">build</i>
        <% end %>
      </div>
    </li>
  </ul>
</div>