config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#home'

  get 'about', to: 'static_pages#about'

  authenticate :user do
    get 'overview', to: 'static_pages#overview'
    get 'search', to: 'static_pages#search'

    resource :settings, only: [:edit, :update]

    resources :sites do

      resources :devices do
        member { get :assign }
        resources :repairs
      end

      resources :supplies do
        member { get :assign, :history, :use }
      end
    end

    get 'all_devices', to: 'devices#all'
    get 'export_devices', to: 'devices#export'
    get 'all_supplies', to: 'supplies#all'
    get 'export_supplies', to: 'supplies#export'

  end

  authenticate :user, lambda { |u| u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
    resources :users_admin, controller: 'users'
  end

end

app/models/supply.rb
class Supply < ApplicationRecord
  resourcify
  has_paper_trail

  has_many :device_supplies
  has_many :devices, through: :device_supplies

  belongs_to :site

  validates :name, presence: true
  validates :vendor, presence: true
  validates :quantity, :threshold, :used, presence: true,
            numericality: { greater_than_or_equal_to: 0, less_than: 2147483648 }

  before_save :add_used_supplies, if: :quantity_changed?, on: :update

  scope :ending_soon, -> { where("quantity <= threshold AND threshold != 0")
                           .order("quantity") }
  scope :all_used, -> { where("used > 0").order("used DESC") }
  scope :most_used, -> { all_used.limit(30) }

  searchkick word_middle: [:name], callbacks: :async

  def search_data
    {
      name: name
    }
  end

  def get_yearly_usage_data(year)
    @supply = self
    @year = year
    @results = {}
    (1..12).each do |month|
      @date = Date.new(@year, month, 1).next_month
      @version = @supply.versions.where(created_at: @date.beginning_of_day .. @date.end_of_day).first
      @results.store(@date.prev_month.strftime("%B"), @version.reify.used) unless @version.nil?
    end
    return @results
  end

  def get_monthly_usage_data(year, month)
    @supply = self
    # Result for the month we pass are in fact available on the next month, i.e. July's results are available in August, because we reset counters on the first day of each month, thus .next_month in date
    @date = Date.new(year, month, 1).next_month
    @results = {}
    @supply_version = @supply.versions.where(created_at: @date.beginning_of_day .. @date.end_of_day).first
    unless @supply_version.nil?
      @unaccounted = @supply_version.reify.used
      @supply.devices.each do |device|
        name = device.name
        device_supply_version = device.device_supplies.where(supply_id: @supply.id).first.versions.where(created_at: @date.beginning_of_day .. @date.end_of_day).first
        unless device_supply_version.nil?
          used = device_supply_version.reify.used
          @results.store(name, used)
          @unaccounted -= used
        end
      end
      @results.store("Unaccounted", @unaccounted) unless @unaccounted == 0
    end
    @results = @results.sort_by { |key, value| value }.reverse.to_h
    return @results
  end

  private

  def add_used_supplies
    # Add substracted amount to :used attribute
    self.used += quantity_was - quantity if !quantity_was.nil? && quantity < quantity_was
  end

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  load_and_authorize_resource

  def index
    @site = Site.find(params[:site_id])
    @supplies = @site.supplies.order("name")
  end

  def all
    @supplies = Supply.includes(:site).accessible_by(current_ability).order("name")
    redirect_to root_path unless Site.any?
  end

  def show
    @site = Site.find(params[:site_id])
    @supply = @site.supplies.find(params[:id])
    @supply_devices = @supply.devices.includes(:site).order("name")
  end

  def new
    @site =  Site.find(params[:site_id])
    @supply = @site.supplies.build
  end

  def edit
    @site =  Site.find(params[:site_id])
    @supply = @site.supplies.find(params[:id])
  end

  def create
    @site =  Site.find(params[:site_id])
    @supply = @site.supplies.build(supply_params)
    if @supply.save
      flash[:success] = "Supply added"
      redirect_to site_supplies_path(@site)
    else
      render 'new'
    end
  end

  def update
    @site = Site.find(params[:site_id])
    @supply = @site.supplies.find(params[:id])

    if @supply.update_attributes(supply_params)
      flash[:success] = "#{@supply.name} saved"
      # Needed for changing Site in form, for site_id to be updated for the redirect
      @supply.reload
      redirect_to site_supply_path(@supply.site, @supply)
      notify
    else
      render 'edit'
    end
  end

  def use
    @site = Site.find(params[:site_id])
    @supply = @site.supplies.find(params[:id])
    @device = Device.find(params[:device_id])
    @device_supply = DeviceSupply.find_by(device_id: @device.id, supply_id: @supply.id)
    if @supply.quantity == 0
      flash[:danger] = "Supply quantity is already 0"
      redirect_to site_device_path(@site, @device)
    else
      @supply.quantity -= 1
      @device_supply.used += 1
      @supply.save
      @device_supply.save
      flash[:warning] = "#{@supply.name} quantity has changed to: #{@supply.quantity}"
      redirect_to site_device_path(@site, @device)
      notify
    end
  end

  def destroy
    Supply.find(params[:id]).destroy
    flash[:warning] = "Supply deleted"
    redirect_to site_supplies_path
  end

  def assign
    @site = Site.find(params[:site_id])
    @supply = @site.supplies.find(params[:id])
    @devices = @site.devices.order("name")
  end

  def export
    if params[:ending]
      @supplies = Supply.includes(:site).ending_soon.accessible_by(current_ability)
    elsif params[:most_used]
      @supplies = Supply.includes(:site).most_used.accessible_by(current_ability)
    elsif params[:all]
      @supplies = Supply.includes(:site).accessible_by(current_ability)
    else
      @site = Site.find(params[:site_id])
      @supplies = @site.supplies
    end

    respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"Supplies.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def history
    @site = Site.find(params[:site_id])
    @supply = @site.supplies.find(params[:id])
    @start_year = (@supply.versions.first.try(:created_at) || Date.today).year
    if params[:report_date]
      @year = params[:report_date][:year].to_i
      @month = params[:report_date][:month].to_i
      if params[:report_types][:report_type] == "Yearly"
        @header = "Month"
        @results = @supply.get_yearly_usage_data(@year)
      elsif params[:report_types][:report_type] == "Monthly"
        @header = "Device"
        @results = @supply.get_monthly_usage_data(@year, @month)
      end
      @total = @results.values.reduce(:+)
    end
  end

  private

  def notify
    if @supply.quantity <= @supply.threshold && !@supply.notified
      SupplyMailer.ending_notification(@supply).deliver_later
      @supply.update_attribute(:notified, true)
    elsif @supply.quantity > @supply.threshold && @supply.notified
      @supply.update_attribute(:notified, false)
    end
  end

  def supply_params
    params.require(:supply).permit(:name, :description, :quantity, :threshold,
                                   :vendor, :site_id, device_ids: [])
  end

end

app/views/supplies/all.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">

        <i class="material-icons left">web_asset</i>

        <!-- Card title -->
        <span class="card-title">All Supplies</span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-supplies-all" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-supplies-all" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button-->
          <li>
            <%= link_to export_supplies_path(all: true, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>

        </ul>

        <% if @supplies.any? %>

          <%= table_for_supplies(@supplies) %>

        <% else %>
          <h5 style="font-size: 1.3em;">Looks like you have no supplies yet.</h5>
        <% end %>

      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/supplies/assign.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">assignment</i>

        <!-- Card title -->
        <span class="card-title"><%= @supply.name %> - Assign Devices</span>

        <div class="container">

          <%= form_for [@site, @supply] do |f| %>

            <table class="highlight">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Type</th>
                  <th>Model</th>
                  <th>Status</th>
                  <th>Location</th>
                </tr>
              </thead>

              <tbody>

                <!-- Needed for successful update if no devices assigned -->
                <%= hidden_field_tag "supply[device_ids][]" %>

                <% @devices.each do |device| %>
                  <tr>
                    <td>
                      <!-- f.object.devices.include?(device) used to set checkbox status, but generates N+1 Query problem. Not sure how to fix that yet. -->
                      <%= check_box_tag "supply[device_ids][]", device.id, f.object.devices.include?(device), id: "supply_device_ids_#{ device.id }" %>
                      <label for="supply_device_ids_<%= device.id %>"><%= device.name %></label>
                    </td>
                    <td><%= device.devtype %></td>
                    <td><%= device.model %></td>
                    <td><%= device.status %></td>
                    <td><%= device.location %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <!-- Buttons -->

            <!-- Uncheck all button -->
            <div class="row">
              <div class="col s12" style="margin-top: 10px; margin-bottom: 10px;">
                <a id="uncheck-all" href="javascript:void(0);" class="btn btn-flat">Uncheck All</a>
              </div>
            </div>

            <div class="row">
              <div class="col s12">

                <!-- Save button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Save" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", site_supply_path(@site, @supply), class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>  <!-- Buttons -->

          <% end %>  <!-- Form end -->

        </div>  <!-- Form container -->
      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<!-- Uncheck all checkboxes function -->
<script>
  $(document).ready(function() {
    $('#uncheck-all').click(function(){
      $("input:checkbox").attr('checked', false);
    });
  });
</script>

app/views/supplies/edit.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">web_asset</i>

        <!-- Supply name -->
        <span class="card-title">Edit: <%= @supply.name %></span>

        <div class="container">

          <%= form_for [@site, @supply] do |f| %>

            <%= form_errors_for @supply %>

            <div class="row">

              <!-- Name -->
              <div class="input-field col s6">
                <%= f.label :name, class: "active" %>
                <%= f.text_field :name, required: true %>
              </div>

              <!-- Vendor -->
              <div class="input-field col s6">
                <%= f.label :vendor, class: "active" %>
                <%= f.text_field :vendor, required: true %>
              </div>
            </div>

            <div class="row">
              <!-- Description -->
              <div class="input-field col s12">
                <%= f.label :description, class: "active" %>
                <%= f.text_field :description %>
              </div>
            </div>

            <div class="row">

              <!-- Quantity -->
              <div class="input-field col s6">
                <%= f.label :quantity, class: "active" %>
                <%= f.number_field :quantity, required: true, min: 0, max: 2147483647 %>
              </div>

              <!-- Ending threshold -->
              <div class="input-field col s6">
                <%= f.label :threshold, "Ending Threshold", class: "active" %>
                <%= f.number_field :threshold, required: true, min: 0, max: 2147483647 %>
              </div>
            </div>

            <!-- Buttons -->
            <div class="row">
              <div class="col s12">

                <!-- Save button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Save" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", site_supply_path(@site, @supply), class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>  <!-- Buttons -->

          <% end %>

        </div>  <!-- Form container -->

        <!-- Delete supply button -->
        <div class="row">
          <div class="col s12">
            <%= button_to "Delete supply", site_supply_path(@site, @supply), data: { confirm: "Are you sure? You're about to delete this supply. This action is irreversible." }, method: :delete, class: "btn btn-flat waves-effect waves-red red-text" %>
          </div>
        </div>

      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/supplies/export.csv.erb
<% headers = ['Name', 'Vendor', 'Description', 'Quantity', 'Used', 'Device Models', 'Site'] %>
<%= CSV.generate_line(headers, { col_sep: "," }) %>
<%- @supplies.each do |supply| -%>
<%= CSV.generate_line( [ supply.name, supply.vendor, supply.description, supply.quantity,
                         supply.used, supply.devices.pluck(:model).uniq.join("; "),
                         supply.site.name ], {col_sep: ","} ).html_safe -%>
<% end %>

app/views/supplies/history.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">

      <div class="card-content">

        <i class="material-icons left">web_asset</i>

        <!-- Supply name -->
        <span class="card-title"><%= @supply.name %> - Usage History</span>

        <form>
          <div class="row">
            <!-- Report Type Select -->
            <div class="input-field col s12 l4">
              <label class="active">Report Type</label>
              <%= select(:report_types, :report_type, ["Yearly", "Monthly"], selected: "Monthly") %>
            </div>

            <!-- Year Select -->
            <div class="input-field col s12 l4">
              <label class="active">Year</label>
              <%= select_year(Date.today, prefix: "report_date", start_year: @start_year, end_year: Date.today.year) %>
            </div>

            <!-- Month Select -->
            <div class="input-field col s12 l4">
              <label class="active">Month</label>
              <%= select_month(Date.today.prev_month, prefix: "report_date") %>
            </div>

          </div>

          <!-- Submit Button -->
          <div class="row">
            <div class="col s12">
              <%= submit_tag "View Report", class: "btn waves-effect waves-light" %>
            </div>
          </div>
          <br>
        </form>

        <!-- Usage information -->
        <% if params[:report_date] %>

          <% if @results.try(:any?) %>

          <!-- Pie Chart -->
          <div class="row">
            <div class="col s12">
              <%= pie_chart @results %>
            </div>
          </div>

            <!-- Table -->
            <div class="row">
              <div class="col s12">
              <table class="highlight">
                <thead>
                  <tr>
                    <th><%= @header %></th>
                    <th>Used</th>
                  </tr>
                </thead>
                <tbody>
                  <% @results.each do |key, value| %>
                    <tr>
                      <td><%= key %></td>
                      <td><%= value %></td>
                    </tr>
                  <% end %>
                  <tr class="grey lighten-3">
                    <td>Total</td>
                    <td><%= @total %></td>
                  </tr>
                </tbody>
              </table>
              </div>
            </div>
          <% else %>
            <!-- Nothing -->
            <div class="row">
              <div class="col s12">
                <h5 style="font-size: 1.3em;">Nothing found</h5>
              </div>
            </div>
          <% end %>
        <% end %>

      </div>  <!-- Card content -->

      <div class="card-action">
        <!-- Back button -->
        <%= link_to "Back", site_supply_path(@site, @supply), class: "btn btn-flat waves-effect waves-light" %>
      </div>

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/supplies/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">

        <i class="material-icons left">web_asset</i>

        <!-- Card title -->
        <span class="card-title"><%= @site.name %> - All Supplies</span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-supplies-all" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-supplies-all" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button-->
          <li>
            <%= link_to export_supplies_path(site_id: @site, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>

        </ul>

        <%= table_for_supplies(@supplies) %>

      </div>  <!-- Card content -->

      <div class="card-action">

        <!-- Back button -->
        <%= link_to "Back", sites_path, class: "btn btn-flat waves-effect waves-light" %>
      </div>

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<div class="fixed-action-btn tooltipped" style="bottom: 45px; right: 24px;" data-position="left" data-delay="50" data-tooltip="Add Supply">
  <%= link_to new_site_supply_path(@site), class: "btn-floating btn-large red" do %>
    <i class="large material-icons">add</i>
  <% end %>
</div>

app/views/supplies/new.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">web_asset</i>

        <!-- Card title -->
        <span class="card-title"><%= @site.name %> - New Supply</span>

        <div class="container">

          <%= form_for [@site, @supply] do |f| %>

            <div class="row">

              <!-- Name -->
              <div class="input-field col s6">
                <%= f.label :name %>
                <%= f.text_field :name, required: true, autofocus: true %>
              </div>

              <!-- Vendor -->
              <div class="input-field col s6">
                <%= f.label :vendor, class: "active" %>
                <%= f.text_field :vendor, required: true %>
              </div>
            </div>

            <div class="row">
              <!-- Description -->
              <div class="input-field col s12">
                <%= f.label :description, class: "active" %>
                <%= f.text_field :description %>
              </div>
            </div>

            <div class="row">

              <!-- Quantity -->
              <div class="input-field col s6">
                <%= f.label :quantity %>
                <%= f.number_field :quantity, required: true, min: 0, max: 2147483647 %>
              </div>

              <!-- Ending threshold -->
              <div class="input-field col s6">
                <%= f.label :threshold, "Ending Threshold", class: "active" %>
                <%= f.number_field :threshold, required: true, min: 0, max: 2147483647 %>
              </div>
            </div>

            <!-- Buttons -->
            <div class="row">
              <div class="col s12">

                <!-- Create button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Create" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", site_path(@site), class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>  <!-- Buttons -->

          <% end %>

        </div>  <!-- Form container -->
      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/supplies/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">

      <div class="card-content">

        <i class="material-icons left">web_asset</i>

        <!-- Supply name -->
        <span class="card-title"><%= @supply.name %></span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-supply-<%= @supply.id %>" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-supply-<%= @supply.id %>" class="dropdown-content" style="min-width: 150px;">

          <!-- Supply history button-->
          <li>
            <%= link_to history_site_supply_path(@site, @supply) do %>
              <i class="material-icons left">history</i>
              History
            <% end %>
          </li>

          <!-- Edit supply button-->
          <li>
            <%= link_to edit_site_supply_path(@site, @supply) do %>
              <i class="material-icons left">edit</i>
              Edit
            <% end %>
          </li>
        </ul>

        <!-- Supply information -->
        <div class="row">
          <div class="col s12">
            <table class="highlight">
              <thead>
                <tr>
                  <th>Vendor</th>
                  <th>Description</th>
                  <th>Quantity</th>
                  <th>Used (Total)</th>
                  <th>Ending Threshold</th>
                  <th>Site</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= @supply.vendor %></td>
                  <td><%= @supply.description %></td>
                  <td><%= @supply.quantity %></td>
                  <td><%= @supply.used %></td>
                  <td><%= @supply.threshold %></td>
                  <td><%= link_to @site.name, @site %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <%= render 'layouts/assets-popout-supply' %>

      </div>  <!-- Card content -->

      <div class="card-action">

        <!-- Back button -->
        <%= link_to "Back", site_path(@site), class: "btn btn-flat waves-effect waves-light" %>
      </div>

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<div class="fixed-action-btn tooltipped" style="bottom: 45px; right: 24px;" data-position="left" data-delay="50" data-tooltip="Assign Devices">
  <%= link_to assign_site_supply_path(@site, @supply), class: "btn-floating btn-large green" do %>
    <i class="material-icons">assignment</i>
  <% end %>
</div>