config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#home'

  get 'about', to: 'static_pages#about'

  authenticate :user do
    get 'overview', to: 'static_pages#overview'
    get 'search', to: 'static_pages#search'

    resource :settings, only: [:edit, :update]

    resources :sites do

      resources :devices do
        member { get :assign }
        resources :repairs
      end

      resources :supplies do
        member { get :assign, :history, :use }
      end
    end

    get 'all_devices', to: 'devices#all'
    get 'export_devices', to: 'devices#export'
    get 'all_supplies', to: 'supplies#all'
    get 'export_supplies', to: 'supplies#export'

  end

  authenticate :user, lambda { |u| u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
    resources :users_admin, controller: 'users'
  end

end

app/models/site.rb
class Site < ApplicationRecord
  resourcify
  has_many :devices, dependent: :destroy
  has_many :supplies, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  load_and_authorize_resource

  def index
    @sites = Site.accessible_by(current_ability).order("name")
    if @sites.empty?
      redirect_to root_path
    end
  end

  def show
    @site = Site.includes(:devices, :supplies).find(params[:id])
    @site_devices = @site.devices
    @site_supplies = @site.supplies
  end

  def new
    @site = Site.new
  end

  def edit
    @site = Site.find(params[:id])
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      flash[:success] = "Site added"
      redirect_to @site
    else
      render 'new'
    end
  end

  def update
    @site = Site.find(params[:id])
    if @site.update_attributes(site_params)
      flash[:success] = "#{@site.name} saved"
      redirect_to @site
    else
      render 'edit'
    end
  end

  def destroy
    Site.find(params[:id]).destroy
    flash[:warning] = "Site deleted"
    redirect_to sites_path
  end

  private

  def site_params
    params.require(:site).permit(:name, :location, :description)
  end

end

app/views/sites/edit.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">domain</i>

        <!-- Site name -->
        <span class="card-title">Edit: <%= @site.name %></span>

        <div class="container">

          <%= form_for @site do |f| %>

            <%= form_errors_for @supply %>

            <!-- Name -->
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">text_fields</i>
                <%= f.label :name, class: "active" %>
                <%= f.text_field :name %>
              </div>
            </div>

            <!-- Location -->
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">location_on</i>
                <%= f.label :location, class: "active" %>
                <%= f.text_field :location %>
              </div>
            </div>

            <!-- Description -->
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">description</i>
                <%= f.label :description, class: "active" %>
                <%= f.text_field :description %>
              </div>
            </div>

            <!-- Buttons -->
            <div class="row">
              <div class="col s12">

                <!-- Update button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Save" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", :back, class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>

          <% end %>

        </div>  <!-- Form container -->

        <!-- Delete site button -->
        <div class="row">
          <div class="col s12">
            <%= button_to "Delete site", @site, data: { confirm: "Are you sure? You're about to delete this site as well as all associated devices and supplies. This action is irreversible." }, method: :delete, class: "btn btn-flat waves-effect waves-red red-text" %>
          </div>
        </div>

      </div>  <!-- Card content -->
    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/sites/index.html.erb
<div class="row">

  <% @sites.each do |site| %>

    <div class="col s12
    <% if @sites.count == 1 %>
      l6 offset-l3
    <% else %>
      l6
    <% end %> ">  <!-- if only one site is present, make it l6 with l3 offset -->
      <div class="card hoverable">
        <div class="card-content">

          <span class="card-title">

            <i class="material-icons left">domain</i>

            <!-- Site name -->
            <%= link_to site.name, site_path(site), class: "black-text" %>

            <!-- Dots Dropdown -->
            <a class="dropdown-button right" href="#!" data-activates="dropdown-site-<%= site.id %>" data-constrainwidth="false">
              <i class="material-icons black-text">more_vert</i>
            </a>

            <!-- Dropdown Structure -->
            <ul id="dropdown-site-<%= site.id %>" class="dropdown-content" style="min-width: 150px;">

              <!-- Edit site button-->
              <li>
                <%= link_to edit_site_path(site) do %>
                  <i class="material-icons left">edit</i>
                  Edit
                <% end %>
              </li>

            </ul>

          </span>

          <table class="highlight">
            <thead>
              <tr>
                <th>Location</th>
                <th>Description</th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td><%= site.location %></td>
                <td><%= site.description %></td>
              </tr>
            </tbody>
          </table>

        </div>  <!-- Card-content -->

        <div class="card-action">

          <%= link_to site_devices_path(site), class: "btn btn-flat waves-effect" do %>
            <i class="material-icons left">print</i>
            View Devices
          <% end %>

          <%= link_to site_supplies_path(site), class: "btn btn-flat waves-effect" do %>
            <i class="material-icons left">web_asset</i>
             View Supplies
          <% end %>

        </div>

      </div>  <!-- Card -->
    </div>  <!-- Col -->

  <% end %>

</div>  <!-- Row -->

<div class="fixed-action-btn tooltipped" style="bottom: 45px; right: 24px;" data-position="left" data-delay="50" data-tooltip="Add Site">
  <%= link_to new_site_path, class: "btn-floating btn-large red" do %>
    <i class="large material-icons">add</i>
  <% end %>
</div>

app/views/sites/new.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">domain</i>

        <!-- Card title -->
        <span class="card-title">New Site</span>

        <div class="container">

          <%= form_for @site do |f| %>

            <!-- Name -->
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">text_fields</i>
                <%= f.text_field :name, required: true, autofocus: true %>
                <%= f.label :name %>
              </div>
            </div>

            <!-- Location -->
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">location_on</i>
                <%= f.text_field :location %>
                <%= f.label :location %>
              </div>
            </div>

            <!-- Description -->
            <div class="row">
              <div class="input-field col s12">
                <i class="material-icons prefix">description</i>
                <%= f.text_field :description %>
                <%= f.label :description %>
              </div>
            </div>

            <!-- Buttons -->
            <div class="row">
              <div class="col s12">

                <!-- Create button -->
                <button class="btn waves-effect waves-light">
                  <%= f.submit "Create" %>
                </button>

                <!-- Back button -->
                <%= link_to "Back", sites_path, class: "btn btn-flat waves-effect waves-light" %>
              </div>
            </div>

          <% end %>

        </div>  <!-- Form container -->

      </div>  <!-- Card content -->

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

app/views/sites/show.html.erb
<div class="row">
  <div class="col s12">
    <div class="card hoverable">
      <div class="card-content">

        <i class="material-icons left">domain</i>

        <!-- Site name -->
        <span class="card-title"><%= @site.name %></span>

        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-site-<%= @site.id %>" data-constrainwidth="false">
          <i class="material-icons black-text">more_vert</i>
        </a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-site-<%= @site.id %>" class="dropdown-content" style="min-width: 150px;">

          <!-- Edit site button-->
          <li>
            <%= link_to edit_site_path(@site) do %>
              <i class="material-icons left">edit</i>
              Edit
            <% end %>
          </li>
        </ul>

        <table class="highlight">
          <thead>
            <tr>
              <th>Location</th>
              <th>Description</th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td><%= @site.location %></td>
              <td><%= @site.description %></td>
            </tr>
          </tbody>
        </table>

        <%= render 'layouts/assets-popout-site' %>

      </div>  <!-- Card content -->

      <div class="card-action">

        <!-- Back button -->
        <%= link_to "Back", sites_path, class: "btn btn-flat waves-effect waves-light" %>
      </div>

    </div>  <!-- Card -->
  </div>  <!-- Col -->
</div>  <!-- Row -->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large red">
    <i class="material-icons">add</i>
  </a>
  <ul>
    <li>
      <div class="tooltipped" data-position="left" data-delay="50" data-tooltip="Add Supply">
        <%= link_to new_site_supply_path(@site), class: "btn-floating green" do %>
          <i class="material-icons">web_asset</i>
        <% end %>
      </div>
    </li>
    <li>
      <div class="tooltipped" data-position="left" data-delay="50" data-tooltip="Add Device">
        <%= link_to new_site_device_path(@site), class: "btn-floating blue" do %>
          <i class="material-icons">print</i>
        <% end %>
      </div>
    </li>
  </ul>
</div>