config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'static_pages#home'

  get 'about', to: 'static_pages#about'

  authenticate :user do
    get 'overview', to: 'static_pages#overview'
    get 'search', to: 'static_pages#search'

    resource :settings, only: [:edit, :update]

    resources :sites do

      resources :devices do
        member { get :assign }
        resources :repairs
      end

      resources :supplies do
        member { get :assign, :history, :use }
      end
    end

    get 'all_devices', to: 'devices#all'
    get 'export_devices', to: 'devices#export'
    get 'all_supplies', to: 'supplies#all'
    get 'export_supplies', to: 'supplies#export'

  end

  authenticate :user, lambda { |u| u.has_role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
    resources :users_admin, controller: 'users'
  end

end

app/views/layouts/_assets-popout-device.html.erb
<!-- Supplies table -->
<div class="row">
  <div class="col s12">
    <ul class="collapsible popout left-align" data-collapsible="expandable">

      <% if @device_supplies.any? %>
        <li>
          <div class="collapsible-header active">
            <i class="material-icons">web_asset</i>
            Assigned Supplies
            <span class="right"><%= @device_supplies.count %></span>
          </div>

          <div class="collapsible-body" style="margin-left: 20px; margin-right: 20px;">

            <%= table_for_supplies(@device_supplies) %>

          </div>
        </li>
      <% end %>

      <% if @repairs.any? %>
        <li>
          <div class="collapsible-header active">
            <i class="material-icons">build</i>
            Last Repairs
            <span class="right"><%= @repairs.count %></span>
          </div>

          <div class="collapsible-body" style="margin-left: 20px; margin-right: 20px;">
            <table class="highlight">
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Status</th>
                  <th>Ticket ID</th>
                  <th>Created</th>
                  <th>Updated</th>
                </tr>
              </thead>
              <tbody>
                <% @repairs.each do |repair| %>
                  <tr>
                    <td><%= link_to truncate(repair.description, length: 80), site_device_repair_path(@device.site, @device, repair) %></td>
                    <td><%= repair.status %></td>
                    <td><%= repair.ticket_id %></td>
                    <td><%= repair.created_at.to_formatted_s(:long) %></td>
                    <td><%= repair.updated_at.to_formatted_s(:long) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </li>
      <% end %>

    </ul>
  </div>
</div>

app/views/layouts/_assets-popout-site.html.erb
<div class="row">
  <div class="col s12">
    <!-- Devices and Supplies Popout -->
    <ul class="collapsible popout left-align" data-collapsible="expandable">

      <% if @site_devices.any? %>

        <li>
          <div class="collapsible-header">
            <i class="material-icons">print</i>
            Devices
            <span class="right"><%= @site_devices.count %></span>
          </div>

          <div class="collapsible-body" style="margin-left: 20px; margin-right: 20px;">

            <%= table_for_devices(@site_devices) %>
            
          </div>
        </li>

      <% end %>

      <% if @site_supplies.any? %>

        <li>
          <div class="collapsible-header">
            <i class="material-icons">web_asset</i>
            Supplies
            <span class="right"><%= @site_supplies.count %></span>
          </div>

          <div class="collapsible-body" style="margin-left: 20px; margin-right: 20px;">

            <%= table_for_supplies(@site_supplies) %>

          </div>
        </li>

      <% end %>

    </ul>  <!-- Devices and Supplies Popout -->
  </div>
</div>

app/views/layouts/_assets-popout-supply.html.erb
<!-- Devices table -->
<div class="row">
  <div class="col s12">
    <% if @supply_devices.any? %>
      <ul class="collapsible popout left-align" data-collapsible="expandable">
        <li>
          <div class="collapsible-header active">
            <i class="material-icons">print</i>
            Assigned Devices
            <span class="right"><%= @supply_devices.count %></span>
          </div>

          <div class="collapsible-body" style="margin-left: 20px; margin-right: 20px;">

            <%= table_for_devices(@supply_devices) %>

          </div>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s6">
          Created with <i class="tiny material-icons">favorite</i> by Daniel Allen.
        </div>
        <div class="col s6">
          <a class="grey-text text-lighten-4 right" href="#">Contact</a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-fixed" style="margin-bottom: 30px;">
  <nav>
    <div class="nav-wrapper" style=" padding-left: 30px; padding-right: 30px;">

      <div class="row">

        <div class="col s3">

          <!-- Hamburger button -->
          <a href="#" data-activates="mobile-menu" class="button-collapse show-on-large" style="margin-right: 20px;"><i class="material-icons" style="font-size: 30px">menu</i></a>

          <!-- Logo -->
          <%= link_to "Boxes", root_path , class: 'brand-logo' %>
        </div>

        <div class="col s6" style="margin-top: 10px; margin-bottom: 10px;">

          <!-- Display search bar if user logged in -->
          <% if current_user %>

            <!-- Search bar -->
            <form class="hide-on-med-and-down" style="height: 44px !important; background-color: #3b464b;">
              <div class="input-field">
                <%= text_field_tag :query, params[:query], placeholder: "Search", type: "search", style: "font-size: 18px; font-weight: 300; border: 0;" %>
              </div>
            </form>

          <% end %>
        </div>

        <div class="col s3">

          <!-- Desktop menu -->
          <ul class="right hide-on-med-and-down">
            <%= render 'layouts/menu' %>
          </ul>
        </div>

      </div>

    </div>
  </nav>
</div>

<!-- Hamburger(mobile) menu -->
<ul class="side-nav" id="mobile-menu">
  <%= render 'layouts/menu-mobile' %>
</ul>

<script>
  $(document).ready(function() {
    $('.button-collapse').sideNav();
    $('.dropdown-button').dropdown();
    $('.collapsible').collapsible();
    $('.tooltipped').tooltip();
    $('select').material_select();
  });
</script>

app/views/layouts/_menu-mobile.html.erb
<!-- If user logged in -->
<% if current_user %>

<!-- Cover view -->
<li><div class="userView">

  <!-- Cover image -->
  <%= image_tag("cover", alt: "Cover", class: "background") %>

  <!-- Userpic stub -->
  <% if current_user.has_role? :admin %>
    <a><i class="material-icons medium white-text">supervisor_account</i></a>
  <% else %>
    <a><i class="material-icons medium white-text">face</i></a>
  <% end %>

  <!-- Full name -->
  <a><span class="white-text name"><%= current_user.full_name %></span></a>

  <!-- Email -->
  <a><span class="white-text email"><%= current_user.email %></span></a>
</div></li>

<!-- Search bar -->
<li class="hide-on-large-only" style="padding: 0 15px 0 15px; margin-top: 48px;">
  <div class="card">
    <form style="height: 45px !important;">
      <!-- <div class="input-field"> -->
        <%= text_field_tag :query, params[:query], placeholder: "Search",  style: "display: block; font-size: 16px; font-weight: 300; width: 100%; height: 45px; margin: 0; box-sizing: border-box; padding: 0 44px 0 15px; border: 0;" %>
        <i class="material-icons" style="color: rgba(0, 0, 0, 0.87); position: absolute; top: 10px; right: 10px;">search</i>
      <!-- </div> -->
    </form>
  </div>

<!-- Home button -->
<li>
  <%= link_to root_path, class: "waves-effect" do %>
    <i class="material-icons left">home</i>
    Home
  <% end %>
</li>

<!-- Sites button -->
<li>
  <%= link_to sites_path, class: "waves-effect" do %>
    <i class="material-icons left">location_city</i>
    Sites
  <% end %>
</li>

<!-- Devices button -->
<li>
  <%= link_to all_devices_path, class: "waves-effect" do %>
    <i class="material-icons left">print</i>
    Devices
  <% end %>
</li>

<!-- Supplies button -->
<li>
  <%= link_to all_supplies_path, class: "waves-effect" do %>
    <i class="material-icons left">web_asset</i>
    Supplies
  <% end %>
</li>

<!-- Reports button -->
<!-- <li>
  <%= link_to "#!", class: "waves-effect" do %>
    <i class="material-icons left">assessment</i>
    Reports
  <% end %>
</li> -->

<li><div class="divider" style="margin-top: 15px; margin-bottom: 15px;"></div></li>

<% if current_user.has_role? :admin %>
<!-- Users button -->
<li>
  <%= link_to users_admin_index_path, class: "waves-effect" do %>
    <i class="material-icons left">face</i>
    Users
  <% end %>
</li>

<!-- Sidekiq -->
<li>
  <%= link_to sidekiq_web_path, class: "waves-effect", target: :_blank do %>
    <i class="material-icons left">work</i>
    Sidekiq
  <% end %>
</li>

<% end %>

<!-- Settings -->
<li>
  <%= link_to edit_settings_path, class: "waves-effect" do %>
    <i class="material-icons left">settings</i>
    Settings
  <% end %>
</li>

<!-- Edit account -->
<li>
  <%= link_to edit_user_registration_path, class: "waves-effect" do %>
    <i class="material-icons left">account_box</i>
    Edit Account
  <% end %>
</li>

<!-- Sign out -->
<li>
  <%= link_to destroy_user_session_path, method: :delete, class: "waves-effect" do %>
    <i class="material-icons left">exit_to_app</i>
    Sign Out
  <% end %>
</li>

<!-- Else display login & about buttons -->
<% else %>

<!-- Login button -->
<li>
  <%= link_to new_user_session_path, class: "waves-effect" do %>
    <i class="material-icons left">account_circle</i>
    Sign in
  <% end %>
</li>

<!-- About button -->
<li>
  <%= link_to about_path, class: "waves-effect" do %>
    <i class="material-icons left">info</i>
    About
  <% end %>
</li>

<% end %>  <!-- end if -->

app/views/layouts/_menu.html.erb
<!-- If user logged in -->
<% if current_user %>

<!-- Account name & icon -->
<li style="margin-right: 5px;">
  <i class="material-icons left">account_circle</i>
  <%= current_user.full_name %>
</li>

<!-- More dots -->
<li>

  <!-- Dropdown button -->
  <a class="dropdown-button" href="#!" data-activates="dropdown-dots" data-beloworigin="true" data-constrainwidth="false">
    <i class="material-icons">more_vert</i>
  </a>

  <!-- Dropdown Structure -->
  <ul id="dropdown-dots" class="dropdown-content" style="min-width: 170px;">

    <!-- Settings -->
    <li>
      <%= link_to edit_settings_path, class: "waves-effect" do %>
        <i class="material-icons left">settings</i>
        Settings
      <% end %>
    </li>

    <!-- Edit account -->
    <li>
      <%= link_to edit_user_registration_path, class: "waves-effect" do %>
        <i class="material-icons left">account_box</i>
        Edit Account
      <% end %>
    </li>

    <li class="divider"></li>

    <!-- Log out -->
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="material-icons left">exit_to_app</i>
        Sign Out
      <% end %>
    </li>

  </ul>

</li>

<!-- Else display login & about buttons -->
<% else %>

<!-- Login button -->
<li>
  <%= link_to new_user_session_path do %>
    <i class="material-icons left">account_circle</i>
    Sign in
  <% end %>
</li>

<!-- About button -->
<li>
  <%= link_to about_path do %>
    <i class="material-icons left">info</i>
    About
  <% end %>
</li>

<% end %>  <!-- end if -->

app/views/layouts/_overview-ending-soon.html.erb
<div class="col s12 l6">
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">
        <i class="material-icons left">timelapse</i>
        Ending soon
        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-supplies-ending" data-constrainwidth="false"><i class="material-icons black-text">more_vert</i></a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-supplies-ending" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button -->
          <li>
            <%= link_to export_supplies_path(ending: true, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>

        </ul>


      </span>

      <% if @supplies_ending.any? %>

        <%= table_for_supplies(@supplies_ending) %>

      <% else %>
        <br>
        <br>
        <p>Nothing</p>
        <br>
      <% end %>
    </div>  <!-- Card content -->
  </div>  <!-- Card -->
</div>  <!-- Col -->

app/views/layouts/_overview-in-repair.html.erb
<div class="col s12">
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">
        <i class="material-icons left">build</i>
        Devices in repair
        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-devices-repair" data-constrainwidth="false"><i class="material-icons black-text">more_vert</i></a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-devices-repair" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button -->
          <li>
            <%= link_to export_devices_path(repair: true, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>

        </ul>
      </span>

      <% if @devices_repair.any? %>

        <%= table_for_devices(@devices_repair) %>

      <% else %>
        <br>
        <br>
        <p>Nothing</p>
        <br>
      <% end %>

    </div>  <!-- Card content -->
  </div>
</div>

app/views/layouts/_overview-most-used.html.erb
<div class="col s12 l6">
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">
        <i class="material-icons left">star</i>
        Most used
        <!-- Dots Dropdown -->
        <a class="dropdown-button right" href="#!" data-activates="dropdown-supplies-most-used" data-constrainwidth="false"><i class="material-icons black-text">more_vert</i></a>

        <!-- Dropdown Structure -->
        <ul id="dropdown-supplies-most-used" class="dropdown-content" style="min-width: 150px;">

          <!-- Export button -->
          <li>
            <%= link_to export_supplies_path(most_used: true, format: "csv") do %>
              <i class="material-icons left">import_export</i>
              Export
            <% end %>
          </li>

        </ul>


      </span>

      <% if @supplies_most_used.any? %>

        <%= table_for_supplies(@supplies_most_used) %>

      <% else %>
        <br>
        <br>
        <p>Nothing</p>
        <br>
      <% end %>
    </div><!-- Card content -->
  </div>
</div>

app/views/layouts/_overview-sites.html.erb
<div class="col s12 l6">
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">
        <i class="material-icons left">location_city</i>
        Sites
        <!-- <i class="material-icons right">more_vert</i> -->
      </span>

      <ul class="collapsible popout" data-collapsible="expandable">

        <% @sites.each do |site| %>
          <li>
            <div class="collapsible-header"><i class="material-icons">business</i><%= site.name %></div>
              <div class="collapsible-body">
                <ul class="collection left-align">

                  <li class="collection-item">
                    <i class="material-icons left">print</i>
                    Total Devices
                    <span class="badge"><%= site.devices.count %></span>
                  </li>

                  <li class="collection-item">
                    <i class="material-icons left">web_asset</i>
                    Total Supplies
                    <span class="badge"><%= site.supplies.count %></span>
                  </li>

                  <li class="collection-item">
                    <i class="material-icons left">build</i>
                    Devices in repair
                    <span class="badge"><%= site.devices.in_repair.count %></span>
                  </li>

                  <li class="collection-item">
                    <i class="material-icons left">timelapse</i>
                    Supplies ending soon
                    <span class="badge"><%= site.supplies.ending_soon.count %></span>
                  </li>

                </ul>
              </div>
          </li>

        <% end %>

      </ul>

    </div>
  </div>
</div>

app/views/layouts/_overview-total.html.erb
<div class="col s12 l6">
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">
        <i class="material-icons left">all_inclusive</i>
        Total
        <!-- <i class="material-icons right">more_vert</i> -->
      </span>

      <ul class="collection left-align">

        <li class="collection-item">
          <i class="material-icons left">location_city</i>
          Sites
          <span class="badge"><%= @sites.count %></span>
        </li>

        <li class="collection-item">
          <i class="material-icons left">print</i>
          Devices
          <span class="badge"><%= @devices.count %></span>
        </li>

        <li class="collection-item">
          <i class="material-icons left">web_asset</i>
          Supplies
          <span class="badge"><%= @supplies.count %></span>
        </li>

      </ul>

    </div>
  </div>
</div>

app/views/layouts/_overview-welcome.html.erb
<div class="col s12">
  <div class="container" style="max-width: 700px;">
    <div class="card-panel hoverable blue-grey lighten-5">
      <i class="material-icons large">dashboard</i>
      <h4>Welcome to Boxes!</h4>
      <br>
      <h5 style="font-size: 1.3em;">Looks like you have no sites yet.</h5>
      <h5 style="font-size: 1.3em;">Create your first site and then you can add devices and suppies to it:</h5>
      <br>
      <%= link_to new_site_path, class: "btn waves-effect waves-light" do %>
        <i class="material-icons left">add</i>
        New Site
      <% end %>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

    <% if Rails.env.production? %>
      <title>Boxes</title>
    <% else %>
      <title>Boxes-DEV</title>
    <% end %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'layouts/header' %>

    <% flash.each do |key, value| %>
      <script>
        Materialize.toast('<%= value %>', 4000)
      </script>
    <% end %>

    <div class="container center-align">
      <%= yield %>
    </div>

    <% if controller?("static_pages") && action?("home") %>
      <%= render 'layouts/footer' %>
    <% end %>

  </body>
</html>